services:
  django-app:
    stdin_open: true
    tty: true
    image: shell_app:latest
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=shell.settings
    init: true
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/app
  postgres-app:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
